{
  "train": {
      image_size: 256,
      batch_size: 64,
      file_path: '/root/data/FFHQ256',
      seed: 43,
      total_steps: 500000,
      sample_steps: 10000,
      save_path: 'result',
      model_path: 'check_points/DiffAE'
  },
  "State": {
    target: modules.state_utils.EMATrainState,
    Input_Shape: [[1,256,256,3],[1,],[1,256,256,3]],
    Model: {
      target: modules.models.diffEncoder.DiffEncoder,
      params: {
        dim: 64,
        out_channels: 3,
        dim_mults: [ 1, 1, 2, 2, 4, 4 ],
        encoder_type: '2D_as_1D',
        latent_type: 'tanh',
        encoder_configs: {
          dims: [ 64,128,256,256 ],
          latent: 2,
          dtype: 'bfloat16',
        }
      }
    },
    Optimizer: {
        target: optax.adamw,
        params: {
          learning_rate: 2.0e-4,
          b1: 0.9,
          b2: 0.99
        }
    },
  },
  "Gaussian": {
    target: modules.gaussian.gaussianDecoder.GaussianDecoder,
    params: {
      sample_shape: [ 256,256,3 ],
      loss: 'l1',
      timesteps: 1000,
      sampling_timesteps: 200,
      objective: 'predict_x0',
      beta_schedule: 'sigmoid',
      min_snr_loss_weight: True,
      scale_shift: True,
      self_condition: True,
      p_loss: False
    },
  }
}