{
  "train": {
      image_size: 256,
      batch_size: 2048,
      file_path: 'pipe:gcloud alpha storage cat gs://luck-eu/data/laion_tar/imagenet_train_shards-{00000..00221}.tar',
      seed: 43,
      total_steps: 5000000,
      sample_steps: 10000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/DiffAE',
      dataset_type: 'gcloud_torch',
      gradient_accumulate_steps: 8
  },
  "State": {
    target: modules.state_utils.EMATrainState,
    Input_Shape: [[1,256,256,3],[1,],[1,256,256,3]],
    Model: {
      target: modules.models.diffEncoder.DiffEncoder,
      params: {
        dim: 64,
        out_channels: 3,
        dim_mults: [ 1, 1, 2, 2, 4],
        encoder_type: '2D',
        latent_type: 'double_z',
        encoder_configs: {
          dims: [ 64,128,256 ],
          latent: 3,
          dtype: 'bfloat16',
        }
      }
    },
    Optimizer: {
        target: optax.lion,
        params: {
          learning_rate: 1.0e-4,
          b1: 0.9,
          b2: 0.99
        }
    },
  },
  "Gaussian": {
    target: modules.score.elucidateAutoEncoder.ElucidateAutoEncoder,
    params: {
      sample_shape: [ 256,256,3 ],
      loss: 'l2',
      kl_loss : 1.0e-6,
    },
  }
}