{
  "train": {
    dataloader_configs: {
      image_size: 64,
      batch_size: 1,
      file_path: '/home/john/data/celeba-128/celeba-128'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 500000,
      sample_steps: 100,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion'
    },

  },
  "Gaussian": {
    target: modules.gaussian.gaussian_multi.GaussianMulti,
    params: {
      sample_shape: [ 64,64,3 ],
      loss: 'l1',
      timesteps: 1000,
      sampling_timesteps: 200,
      objective: 'predict_noise',
      beta_schedule: 'sigmoid',
      min_snr_loss_weight: True,
      scale_shift: True,
      self_condition: True,
      p_loss: False
    },
  },
"State": {
    target: modules.state_utils.EMATrainState,
    Input_Shape: [[1,256,256,3],[1,],[1,256,256,3]],
    Model: {
      target: modules.models.diffEncoder.DiffEncoder,
      params: {
        dim: 64,
        out_channels: 3,
        dim_mults: [ 1, 1, 2, 2, 4, 4 ],
        encoder_type: '2D',
        encoder_configs: {
          dims: [ 64,128,256,256,256 ],
          latent: 16,
          dtype: 'bfloat16',
        }
      }
    },
    Optimizer: {
        target: optax.adamw,
        params: {
          learning_rate: 2.0e-4,
          b1: 0.9,
          b2: 0.99
        }
    },
  },

  states_conf: [
     {
      objective: "predict_x0",
      time_min: 0,
      time_max: 500,
    },
    {
      objective: "predict_noise",
      time_min: 500,
      time_max: 1000,
    },
  ]



}