{
  "train": {
    dataloader_configs: {
      image_size: 64,
      batch_size: 8,
      file_path: '/home/john/data/celeba-512'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 500000,
      sample_steps: 100,
      save_path: 'result/SR',
      model_path: 'check_points/SR'
    },
    optimizer: "AdamW",
    optimizer_configs: {
      learning_rate: 1.0e-4
    }

  },
  "Unet": {
    dim: 32,
    out_channels: 3,
    dim_mults: [1, 2, 4, 4, 8, 8]
#    layers_per_block: 2,
#    block_out_channels: [
#      128, 256, 256, 512
#    ],
#    scale : 1,
#    dtype : 'bfloat16',
#    precision : 'highest'
  },
  "Gaussian": {
    loss: 'l2',
    timesteps: 1000,
    sampling_timesteps: 75,
    objective: 'predict_noise',
    beta_schedule : 'linear',
    sr_factor: 4
  }

}