{
  "train": {
    dataloader_configs: {
      image_size: 256,
      batch_size: 8,
      file_path: '/home/john/data/celeba-512'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 500000,
      sample_steps: 10000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion'
    },

  },
  "Unet": {
    target: modules.models.unet.Unet,
    optimizer: {
      optimizer: optax.adamw,
      optimizer_configs: {
        learning_rate: 1.0e-4
      }
    },
    params:{
      dim: 32,
      out_channels: 3,
      dim_mults: [ 1, 2, 4, 4, 8, 8 ],
      self_condition: True,
      use_encoder : True,
      encoder_configs :{
        dims: [ 64,128,256,256 ],
        dtype: 'bfloat16',
      }
    }
  },
  "Gaussian": {
    loss: 'l1',
    timesteps: 1000,
    sampling_timesteps: 200,
    objective: 'predict_noise',
    beta_schedule: 'sigmoid',
    min_snr_loss_weight: True,
    scale_shift: True,
  }

}