{
  "train": {
    dataloader_configs: {
      image_size: 256,
      batch_size: 32,
      file_path: '/home/john/data/FFHQ256'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 500000,
      sample_steps: 10000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion'
    },

  },
  FirstStage :{
    "AutoEncoder": {
      target: modules.models.diffEncoder.DiffEncoder,
      optimizer: {
        optimizer: optax.adamw,
        optimizer_configs: {
          learning_rate: 2.0e-4,
          b1: 0.9,
          b2: 0.99
        }
      },
      params: {
        dim: 64,
        out_channels: 3,
        dim_mults: [ 1, 1, 2, 2, 4, 4 ],
        encoder_type: '2D',
        encoder_configs: {
          dims: [ 64,128,256,256,256 ],
          latent: 16,
          dtype: 'bfloat16',
        }
      }
    },

    "Gaussian": {
        target: modules.gaussian.gaussian_test.GaussianTest,
        params:{
          sample_shape: [ 256,256,3 ],
          loss: 'l1',
          timesteps: 1000,
          sampling_timesteps: 200,
          objective: 'predict_noise',
          beta_schedule: 'sigmoid',
          min_snr_loss_weight: True,
          scale_shift: True,
          self_condition: True,
          p_loss: False
        }
    }
  },


}