{

  "FirstStage": {
    "AutoEncoder": {
            target: modules.models.diffEncoder.DiffEncoder,
            optimizer: {
              optimizer: optax.adamw,
              optimizer_configs: {
                learning_rate: 2.0e-4,
                b1: 0.9,
                b2: 0.99
              }
            },
            params: {
              dim: 64,
              out_channels: 3,
              num_res_blocks: 2,
              dim_mults: [ 1, 1, 2, 2, 4, 4 ],
              encoder_type: '1D',
              encoder_configs: {
                dims: [ 64,128,256,256,512,512,512 ],
                dtype: 'bfloat16',
                latent: 512,
              }
            }
          },
          "Gaussian": {
            target: modules.gaussian.gaussian_test.GaussianTest,
            params: {
              sample_shape: [ 128,128,3 ],
              loss: 'l1',
              timesteps: 1000,
              sampling_timesteps: 200,
              objective: 'predict_noise',
              beta_schedule: 'sigmoid',
              min_snr_loss_weight: True,
              scale_shift: True,
              self_condition: True,
              p_loss: False
            }
          }
  },
  "train": {
    dataloader_configs: {
      image_size: 128,
      batch_size: 4096,
      file_path: '/home/john/data/latent1D',
      data_type: 'np'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 3000000,
      sample_steps: 50000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion'
    },
  },
  "State": {
      target: modules.state_utils.EMATrainState,
      Input_Shape: [ [ 1,512 ],[ 1, ] ],
      Model: {
        target: modules.models.latentnet.LatentNet,
        params: {
          num_layers: 10,
          dim: 512,
          out_dim: 512,
          dtype: 'bfloat16'
        }
     },
      Optimizer: {
        target: optax.lion,
        params: {
          learning_rate: 1.0e-4,
        }
      },
  },
  "Gaussian": {
    target: modules.gaussian.gaussian.Gaussian,
    params: {
      sample_shape: [ 512 ],
      loss: 'l2',
      timesteps: 1000,
      sampling_timesteps: 200,
      objective: 'predict_noise',
      beta_schedule: 'cosine',
      #min_snr_loss_weight: True,
      #scale_shift: True,
      #self_condition: True,
      p_loss: False
    },
  }
}



