{
  "train": {
      image_size: 128,
      batch_size: 1,
      file_path: '/home/john/data/celeba-128/celeba-128',
      seed: 43,
      total_steps: 500000,
      sample_steps: 10000,
      save_path: 'result',
      model_path: 'check_points/SR'
  },
  "State": {
    target: modules.state_utils.EMATrainState,
    Input_Shape: [ [ 1,128,128,3 ],[ 1, ] ,[ 1,128,128,3 ]],
    Model: {
      target: modules.models.unet.Unet,
      params: {
        dim: 32,
        out_channels: 3,
        dim_mults: [ 1, 2, 4, 4, 8, 8 ],
      }
    },
    Optimizer: {
      target: optax.adamw,
      params: {
        learning_rate: 2.0e-4,
        b1: 0.9,
        b2: 0.99
      }
    },
  },
  "Gaussian": {
    target: modules.gaussian.gaussianSR.GaussianSR,
    params: {
      sample_shape: [ 128,128,3 ],
      loss: 'l1',
      timesteps: 1000,
      sampling_timesteps: 200,
      objective: 'predict_noise',
      beta_schedule: 'cosine',
      sr_factor: 8,
      p_loss: False
    },
  },
}