{
  "train": {
      image_size : 256,
      seed : 43,
      batch_size : 64,
      file_path : '/root/data/celeba-512',
      learning_rate : 1.0e-4,
      optimizer : "AdamW",
      sample_steps : 100

  },
  "Unet": {
    dim: 48,
    out_channels: 3,
    dim_mults: [1, 2, 4, 4, 8, 8]
  },
  "Gaussian": {
    loss: 'l2',
    timesteps: 1000,
    sampling_timesteps: 100,
    objective: 'predict_noise',
    beta_schedule : 'sigmoid',
  }

}