{

  "FirstStage": {
    "AutoEncoder": {
          target: modules.models.diffEncoder.DiffEncoder,
              optimizer: {
                optimizer: optax.adamw,
                optimizer_configs: {
                  learning_rate: 2.0e-4,
                    b1: 0.9,
                    b2: 0.99
                }
              },
                params: {
                  dim: 64,
                  out_channels: 3,
                  dim_mults: [ 1, 1, 2, 2, 4, 4 ],
                  encoder_type: '2D',
                  encoder_configs: {
                    dims: [ 64,128,256,256 ],
                    dtype: 'bfloat16',
                  }
                }
          },
          "Gaussian": {
            target: modules.gaussian.gaussian_test.GaussianTest,
            params: {
              image_size: 128,
              loss: 'l1',
              timesteps: 1000,
              sampling_timesteps: 200,
              objective: 'predict_noise',
              beta_schedule: 'sigmoid',
              min_snr_loss_weight: True,
              scale_shift: True,
              self_condition: True,
              p_loss: False
            }
          }
  },
  "train": {
    dataloader_configs: {
      image_size: 128,
      batch_size: 1024,
      file_path: '/root/data/latent2D',
      data_type: 'np',
      repeat: 100,

    },
    trainer_configs: {
      seed: 43,
      total_steps: 3000000,
      sample_steps: 50000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion'
    },
  },
  "LatentNet": {
    target: modules.models.unet.Unet,
    input_shape: [[1,16,16,4],[1],[1,16,16,4]],
    optimizer: {
      optimizer: optax.lion,
      optimizer_configs: {
        learning_rate: 1.0e-4,
        b1: 0.9,
        b2: 0.99
      }
    },
    params: {
      dim: 64,
      #num_res_blocks : [2,2,2,2],
      dim_mults: [ 1,2,4,8 ],
      #out_dim: 3,
      out_channels: 4,
      dtype: 'bfloat16',
      #patch_size: 1
      self_condition: True
    }
  },
  "Gaussian": {
    target: modules.gaussian.gaussian.Gaussian,
    params: {
      image_size: 16,
      loss: 'l2',
      timesteps: 1000,
      sampling_timesteps: 200,
      objective: 'predict_mx',
      beta_schedule: 'cosine',
      #min_snr_loss_weight: True,
      #scale_shift: True,
      self_condition: True,
      p_loss: False
    },
  }
}