{
  "FirstStage": {
      State: {
        target: modules.state_utils.EMATrainState,
        Input_Shape: [ [ 1,128,128,3 ],[ 1, ] ,[ 1,128,128,3 ]],
        Model: {
          target: modules.models.diffEncoder.DiffEncoder,
          params: {
              dim: 64,
              out_channels: 3,
              dim_mults: [ 1, 1, 2, 2, 4, 4 ],
              encoder_type: '2D',
              latent_type: 'clip',
              encoder_configs: {
                dims: [ 128,128,256,512 ],
                latent: 4,
                dtype: 'bfloat16',
              }
            }
          },
        Optimizer: {
          target: optax.sgd,
          params: {
                learning_rate: 1.0e-4
          }
        },
      },
      "Gaussian": {
        target: modules.score.elucidateAutoEncoder.ElucidateAutoEncoder,
        params: {
          sample_shape: [ 256,256,3 ],
          loss: 'l2',
          apply_method: modules.models.diffEncoder.DiffEncoder.decode
        },
      }
  },
  "train": {
      image_size: 256,
      batch_size: 512,
#      file_path: '/root/data/latent2D-16',
      file_path: '/home/john/data/FFHQ256',
      data_type: 'img',
      repeat: 1,
      seed: 43,
      total_steps: 3000000,
      sample_steps: 50000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion',
      gradient_accumulate_steps: 512

  },
  State: {
    target: modules.state_utils.EMATrainState,
    Input_Shape: [ [ 1,32,32,4 ],[ 1, ] ],
#    apply_fn: modules.models.diffEncoder.DiffEncoder.encode,
    Model: {
      target: modules.models.unet.Unet,
      params: {
        dim: 128,
        num_res_blocks : [2,2,2,2],
        dim_mults: [ 1,2,4,4 ],
        out_channels: 4,
        dtype: 'bfloat16',
#        self_condition: True
        }
    },
    Optimizer: {
      target: optax.lion,
      params: {
        learning_rate: 3.0e-5,
        weight_decay: 0.01
      }
    },
  },
  "Gaussian": {
    target: modules.score.elucidate.ElucidatedDiffusion,
    params: {
      sample_shape: [ 32,32,4 ],
      loss: 'l2',
    },
  }
}