{
  "train": {
      image_size : 128,
      seed : 43,
      batch_size : 64,
      file_path : '/root/data/flowers',
      learning_rate : 1.0e-4,
      optimizer : "AdamW",
      sample_steps : 50000

  },
  "Unet": {
    out_channels: 3,
    dtype : 'bfloat16',
    self_condition : True
  },
  "Gaussian": {
    loss: 'l1',
    timesteps: 1000,
    sampling_timesteps: 75,
    objective: 'predict_noise',
    beta_schedule : 'sigmoid',
     self_condition : True,
    scale_shift : True

  }

}