{
  "train": {
      image_size : 64,
      seed : 43,
      batch_size : 128,
      file_path : '/root/data/celeba-128/celeba-128'
  },
  "Unet": {
    out_channels: 3,
    layers_per_block: 2,
    block_out_channels: [
      256, 512, 512, 1024
    ],
    scale : 1,
    dtype : 'bfloat16'
  },
  "Gaussian": {
    loss: 'l2',
    timesteps: 1000,
    sampling_timesteps: 100,
    objective: 'predict_x0',
    beta_schedule : 'cosine'
  }

}