{
  "train": {
      image_size : 128,
      seed : 43,
      batch_size : 4,
      file_path : '/home/john/data/flowers',
      learning_rate : 3.0e-5,
      optimizer : "Lion",
      sample_steps : 50000

  },
  "Unet": {
    out_channels: 3,
    dtype : 'bfloat16',
    self_condition : True
  },
  "Gaussian": {
    loss: 'l1',
    timesteps: 1000,
    sampling_timesteps: 75,
    objective: 'predict_noise',
    beta_schedule : 'sigmoid',
    min_snr_loss_weight : True,
    scale_shift : True,
    self_condition : True

  }

}