{
  "train": {
      image_size: 64,
      batch_size: 1024,
      file_path: '/root/data/celeba-128/celeba-128',
      seed: 43,
      total_steps: 5000000,
      sample_steps: 10000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion',
      gradient_accumulate_steps: 32
  },
  "State": {
    target: modules.state_utils.EMATrainState,
    Input_Shape: [ [ 1,64,64,3 ],[ 1, ] ],
    Model: {
      target: modules.models.unet.Unet,
      params: {
        dim: 128,
        out_channels: 3,
        dim_mults: [ 2, 2, 2 ],
        num_res_blocks: 4,
      }
    },
    Optimizer: {
      target: optax.adamw,
      params: {
        learning_rate: 1.0e-3,
        b1: 0.9,
        b2: 0.99,
        weight_decay: 0.0001
      }
    },
  },
  "Gaussian": {
    target: modules.gaussian.gaussian.Gaussian,
    params: {
      sample_shape: [ 64,64,3 ],
      loss: 'l1',
      timesteps: 1000,
      sampling_timesteps: 200,
      objective: 'predict_noise',
      beta_schedule: 'linear',
#      scale_factor: 0.5,
      p_loss: False
    },
  },
}