{
  "train": {
    dataloader_configs: {
      image_size: 128,
      batch_size: 64,
      file_path: '/root/data/celeba-128/celeba-128'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 500000,
      sample_steps: 10000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion'
    },

  },
  "Unet": {
    target: modules.models.test_unet.Unet,
    optimizer: {
      optimizer: optax.adam,
      optimizer_configs: {
        learning_rate: 2.0e-4,
        b1: 0.9,
        b2: 0.99
      }
    },
    params:{
      dim: 64,
      #num_res_blocks : [2,2,2,2],
      #dim_mults: [1,2,3,4],
      out_dim: 3,
      #out_channels: 3,
      dtype: 'float32',
      #patch_size: 1
      #self_condition: True
    }
  },
  "Gaussian": {
    loss: 'l2',
    timesteps: 1000,
    sampling_timesteps: 200,
    objective: 'predict_noise',
    beta_schedule: 'cosine',
    #min_snr_loss_weight: True,
    scale_shift: True,
    noise_type: 'pyramid'
    #self_condition: True,

  }

}