{
  "train": {
      image_size: 64,
      batch_size: 64,
      file_path: '/root/data/s',
      seed: 43,
      total_steps: 5000000,
      sample_steps: 10000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion'
  },
  "State": {
    target: modules.state_utils.EMATrainState,
    Input_Shape: [ [ 1,64,64,3 ],[ 1, ] ],
    Model: {
      target: modules.models.unet.Unet,
      params: {
        dim: 128,
        out_channels: 3,
        dim_mults: [ 2, 2, 2 ],
        num_res_blocks: 4,
      }
    },
    Optimizer: {
      target: optax.adamw,
      params: {
        learning_rate: 8.0e-5,
        b1: 0.9,
        b2: 0.99
      }
    },
  },
  "Gaussian": {
    target: modules.score.elucidate_pmap.ElucidatedDiffusion,
    params: {
      sample_shape: [ 64,64,3 ],
      loss: 'l2',
#      timesteps: 1000,
#      sampling_timesteps: 200,
#      objective: 'predict_noise',
#      beta_schedule: 'cosine',
#      scale_factor: 0.5,
#      p_loss: False
    },
  },
}