{
  "train": {
    dataloader_configs: {
      image_size: 64,
      batch_size: 16,
      file_path: '/home/john/data/celeba-128/celeba-128'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 500000,
      sample_steps: 10000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion'
    },

  },
  "Unet": {
    target: modules.models.unet.Unet,
    optimizer: {
      optimizer: optax.adamw,
      optimizer_configs: {
        learning_rate: 5.0e-5
      }
    },
    params:{
      dim: 64,
      num_res_blocks: [ 1,1,1,5 ],
      out_channels: 3,
      dtype: 'bfloat16',
      patch_size: 1
      #self_condition: True
    }
  },
  "Gaussian": {
    loss: 'l2',
    timesteps: 1000,
    sampling_timesteps: 200,
    objective: 'predict_noise',
    beta_schedule: 'sigmoid',
#    min_snr_loss_weight: True,
#    scale_shift: True,
    #self_condition: True,

  }

}