{
  "train": {
    dataloader_configs: {
      image_size: 64,
      batch_size: 8,
      file_path: '/home/john/data/s'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 500000,
      sample_steps: 10000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion'
    },

  },
  "Unet": {
    target: modules.models.unet.UVit,
    optimizer: {
      optimizer: optax.adamw,
      optimizer_configs: {
        learning_rate: 1.0e-4
      }
    },
    params:{

    }
  },
  "Gaussian": {
    loss: 'l1',
    timesteps: 1000,
    sampling_timesteps: 200,
    objective: 'predict_x0',
    beta_schedule: 'cosine',


  }

}