{
  "train": {
    dataloader_configs: {
      image_size: 128,
      batch_size: 8,
      file_path: '/home/john/data/celeba-512'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 500000,
      sample_steps: 10000,
      save_path: 'result/Diffusion',
      model_path: 'check_points/Diffusion'
    },
    optimizer:  optax.adamw,
    optimizer_configs: {
      learning_rate: 1.0e-4
    }

  },
  "Unet": {
    target: modules.models.unet.Unet,
    params:{
      out_channels: 3,
      dtype: 'bfloat16',
      self_condition: True
    }
  },
  "Gaussian": {
    loss: 'l1',
    timesteps: 1000,
    sampling_timesteps: 200,
    objective: 'predict_noise',
    beta_schedule: 'sigmoid',
    min_snr_loss_weight: True,
    scale_shift: True,
    self_condition: True,
    sr_factor : 4

  }

}