{
  "train": {
    dataloader_configs: {
      image_size: 256,
      batch_size: 24,
      file_path: '/root/data/FFHQ256'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 500000,
      sample_steps: 10000,
      save_path: 'result/AutoEncoder',
      model_path: 'check_points/AutoEncoder',
      disc_start : 50000
    },


  },
  "AutoEncoder": {
    target : modules.models.autoencoder.AutoEncoderKL,
    optimizer :{
        optimizer: optax.adamw,
        optimizer_configs: {
          learning_rate: 4.5e-6,
          b1: 0.5,
          b2: 0.9
        }
    },
    params : {
      dims: [ 128,256,512,512 ],
      dtype: 'bfloat16',
      #use_attn : True
    }
  },
  "Discriminator": {
      target : modules.models.discriminator.NLayerDiscriminator,
      optimizer: {
        optimizer: optax.adamw,
        optimizer_configs: {
          learning_rate: 4.5e-6,
          b1: 0.5,
          b2: 0.9
        }
      },
      params : {

    }

  }

}