{
  "train": {
      dataloader_configs : {
        image_size : 256,
        batch_size : 8,
        file_path : '/home/john/data/celeba-128/celeba-128'
      },
      trainer_configs:{
          seed : 43,
          total_steps : 500000,
          sample_steps : 100,
          save_path : 'result/AutoEncoder',
          model_path : 'check_points/AutoEncoder'
      },
      optimizer : "AdamW",
      optimizer_configs : {
        learning_rate : 1.0e-4
      }

  },
  "AutoEncoder": {
    dims : [64,128,256],
    dtype : 'bfloat16'
  }
}