{
  "train": {
    dataloader_configs: {
      image_size: 128,
      batch_size: 16,
      file_path: '/home/john/data/FFHQ'
    },
    trainer_configs: {
      seed: 43,
      total_steps: 500000,
      sample_steps: 10000,
      save_path: 'result/AutoEncoder',
      model_path: 'check_points/AutoEncoder',
      disc_start : 50000
    },


  },
  "AutoEncoder": {
    target : modules.models.autoencoder.AutoEncoderKL,
    optimizer :{
        optimizer: optax.adamw,
        optimizer_configs: {
          learning_rate: 1.0e-4
        }
    },
    params : {
      dims: [ 64,128,256 ],
      dtype: 'bfloat16',
      #block_type : 'rep'
    }
  },
  "Discriminator": {
      target : modules.models.discriminator.NLayerDiscriminator,
      optimizer: {
        optimizer: optax.adamw,
        optimizer_configs: {
          learning_rate: 1.0e-3
        }
      },
      params : {

    }

  }

}